using GammaJul.ReSharper.ForTea.Psi;
using JetBrains.DocumentModel;
using JetBrains.ProjectModel;
using JetBrains.ReSharper.Daemon.Impl;

namespace GammaJul.ReSharper.ForTea.Daemon
{
    /// <summary>
    /// Advises ReSharper to skip analysis of files generated by TextTemplatingFilePreprocessor because we provide an alternative in-memory representation.
    /// </summary>
    /// <see cref="T4CSharpCodeGenerator"/>
    [SolutionComponent]
    internal class DisableRuntimeT4CodeBehindAnalysis : IDaemonAutoDisableStrategy
    {
        public bool AnylysisIsNotRecommended(IDocument document, IProjectFile file)
        {
            return file.GetDependsUponFile().IsPreprocessedT4Template();
        }
    }
}
